### ISSUE TITLE
How does spiffe manage life cycle of x509 SVID?

### ISSUE THREAD

**Issue by t57root** [spiffe/spiffe#105]
Does spiffe use expiration time or certificates revocation to manage life cycle of x509 certificates? I can't find any document regarding this.
Thanks in advance!

**Comment by spikecurtis** [comment]
The primary mechanism is via expiration time. In the SPIFFE architecture workloads have an API to the control plane to get certificate updates automatically, so the vision is for the control plane to keep the expiration times for certificates very short (compared with typical Web PKI cert lifetimes).

Root CA certificates can be "revoked" by updating the trust bundle delivered to workloads over the API.

We have briefly discussed whether to implement an explicit certificate revocation mechanism for non-root-CA certs, but we haven't pinned down specific requirements for such a proposal. If this is something your application/organization is interested in, we'd love to hear about your use case & requirements.

**Comment by t57root** [comment]
@spikecurtis Thanks for the kind explanation. 

I noticed that Google ALTS use certificate revocation and a long time expiration time in case it encounters a clock sync issue or a certificate rotation failure.  So what I concern is that using a short expiration time makes the certificate rotation service as a single point of failure.  For short live certificates, using revocation instead of expiration should make the CRL (maybe in OCSP-stapling) growing larger very quickly whithin one expiration period. But it seems google doesn’t make it clear regarding how they deal with the growing speed of CRL in their paper.

Is there some mechanism of fault tolerance in SPIFFE?  Or SPIFFE simply assume that rotation service is definitely usable? Which seems how Netflix deal with this problem. If so, why not deal with this the google way?  

Also I think a revocation mechanism is necessary because an organization would want to immediately revoke the certificates of some machines in a security incident response.

**Comment by spikecurtis** [comment]
SPIFFE itself is an architecture and set of API specs. It is designed to be compatible with fault tolerant techniques, but does not specifically require them. Our expectation is that most production implementations will support high-availability via redundancy.

SPIFFE does assume that the Workload API is available in order to start new workloads. But note that the world does not grind to a halt immediately if the Workload API is not available: existing workloads continue operating normally until certificates expire. Here operators will need to make some trade-offs. Setting expiration to be 24 hours would give the operator many hours to bring the Workload API back online before significant service disruption. Which, if it happened monthly is just 99% uptime.  If the operator wanted to shorten expiration to, say 1 hour, they would need a corresponding increase in uptime, to 99.9%.

**Comment by t57root** [comment]
Thanks, rotating certificates a few hours/days ahead of expiration is indeed a fault tolerance mechanism.
