### ISSUE TITLE
JWT-SVID Standardisation

### ISSUE THREAD

**Issue by ionut-arm** [spiffe/spiffe#120]
Hello!

The project we're working on, [Parsec](https://github.com/parallaxsecond/parsec), is planning on using some sort of tokens for identifying and authenticating clients, and JWT seemed the best choice for this, aiming towards having a SPIFFE'ish environment. 

Reading about the issues created by the complexity of the JOSE specs and the vulnerabilities in some JWT libraries means that your [JWT-SVID](https://github.com/spiffe/spiffe/blob/master/standards/JWT-SVID.md) restriction on JWT sounds quite appealing from a security perspective. However, the document mentions that 

> This document specifies an experimental identity document standard for the internet community, and requests discussion and suggestions for improvements. It is a work in progress.

How stable can that spec be considered? There seem to have been relatively few changes made since its inception.

**Comment by evan2645** [comment]
Hello @ionut-arm 

> How stable can that spec be considered? There seem to have been relatively few changes made since its inception.

As you've noticed, the spec is very stable. I think I speak for all the maintainers when I further say that we're committed to maintaining compatibility, and you should reasonably expect that any future changes won't inhibit interoperability.

We have loosely discussed how we might introduce changes that have compatibility impacts, with brief consensus around versioning. That said, if we were to introduce changes at this point, I'd say it's more likely that we'd introduce a new token type altogether rather than rev this one. There are many things we'd like to see in a security token that JWT isn't well suited for.

**Comment by ionut-arm** [comment]
Hi @evan2645 

Thank you for the reply, it's useful to have an official word on this! 😃 We'll be monitoring the evolution of your token-of-choice.
