### ISSUE TITLE
Define administrative and default SVID ordering

### ISSUE THREAD

**Issue by bri365** [spiffe/spiffe#156]
In cases where more than one SVID is returned for a workload, it is desirable to understand and/or control the ordering in which they are delivered and may be applied. This is currently undefined in the specification. I believe both an administrative component (e.g. a priority field in the X509SVID message) and a default component (e.g. SVID sorting) should be defined in some way. This would allow, but not require, control plane management as well as offer a solution for both default ordering so as not to require control plane operations as well as control plane conflicts where two or more SVIDs end up with the same ordering metadata.

It is possible that administrative selection of default SVIDs is outside the scope of this specification, and will be left to server implementations. In that case, some standard default mechanism should probably still be defined here.

**Comment by bri365** [comment]
A defined default behavior should also protect users from having the ordering change out from under them if they switch or federate across SPIFFE runtimes

**Comment by azdagron** [comment]
I personally think the semantics around SVID ordering in the Workload API response is tricky and a bit of a footgun. For workloads that don't care, the ordering semantics are irrelevant. Those workloads don't have an opinion so the first SVID is as good as any to them. However, if the number of SVIDs is greater than one, and the workload needs to somehow reason about which one to choose, order is a terrible and brittle way for it to make a selection. It would be trivial for an administrative error to influence the ordering which could have staggering security impact (like for example, using an internal-facing SVID with an external service).

This isn't the first time this has come up however. In the past we've had loose discussions around adding an opaque "tag", "label", or "use" value to the SVID field in the Workload API response. This gives administrators a way to indicate what the SVID is intended for, and provides a way for workloads to sharpshoot an SVID out of the response for a particular use. ~Workloads that don't care could look for any that aren't labelled, or in the absence, otherwise choose an arbitrary one...~ (changed my mind.... still thinking about this)

**Comment by azdagron** [comment]
> Workloads that don't care could look for any that aren't labelled, or in the absence, otherwise choose an arbitrary one...

Hmm, strike that.

**Comment by spikecurtis** [comment]
@bri365 can you talk about purpose or task being solved that SVID ordering would help with?

My mental model for the case when there is more than one SVID available is that the workload needs to choose an SVID for a particular purpose (e.g. open a TLS connection, or make a request using a JWT).  In that case, order is at best a stand-in for some higher level concept, like "is this a internal or external connection?" or "what role do I have in the transaction?"  In that case it makes sense to me that if we provide any metadata, it should be richer than ordering information.  However, maybe there is some other use case that you're thinking of?

**Comment by bri365** [comment]
Thanks @azdagron and @spikecurtis for the engagement!

First off, I want to say that workloads expecting to see multiple IDs really ought to handle that themselves, by design and with awareness of what each may be used for - I believe that is in keeping with the spirit of the SPIFFE spec as written and envisioned. I think trying to solve that administratively or any other way is a high risk, low reward endeavor.

The spirit of this issue, as I see it, is in addressing the transient or degenerate cases where workloads are (temporarily or permanently) unaware of the possibility of multiple IDs.

There are a couple of cases that have been presented:

1) "upgrading" SPIFFE IDs for a set of workloads - often this results from some organizational standardization effort around SPIFFE IDs, and initial adopters find themselves out of compliance and need to change. In the face of rolling updates and keeping the lights on, the new SPIFFE ID is created alongside the old one and workloads adopt the new one as they are restarted or updated. In this case, enhancing a workload to be multi-ID aware is generally not worth the development effort. Administrative prioritization of SPIFFE IDs would effectively solve this problem in the long term, after workload registration engine updates with the new metadata propagate through the environment. A deterministic sorting algorithm with existing protobuf messages provides short term relief for users wishing to safely migrate before the metadata solution is available. While not elegant, a simple "reverse sort order" flag to spire could handle cases where the desired future SPIFFE ID is lengh/lexicographically further down the line.

2) "default" behavior for collisions, either where administrative metadata collides (e.g. two SPIFFE IDs with the same priority) or multiple SPIFFE IDs result from incomplete attestation response. The former case is somewhat easier to refer back to the user, as difficult as the actual implementation may be. The latter, however, appears to be a real issue, as demonstrated by the long conversations and concerns around negated selectors. Given the high value SPIRE (and presumably other runtime implementations) place on keeping things running, partial attestation, when deemed sufficient, may result in multiple SPIFFE IDs. Further, the logic trees for these scenarios will likely rapidly evolve beyond simple administration metadata solutions. In both cases, a deterministic ordering of IDs allows for predictable behavior, or at least as predictable as possible.

Given these, I believe a solution of BOTH administratively controlled metadata (an integer priority field is my current favorite proposal) AND a default ordering of IDs (almost anything is better than random UUIDs) offers users the best protection for predictable operation of this critical security infrastructure.

**Comment by spikecurtis** [comment]
When I read your message initially, I thought you were talking about the ordering of SVIDs returned on the Workload API.  But, now reading your use case about "upgrading" I'm not so sure.  In the case where the workloads are getting migrated to a new SPIFFE ID, it doesn't seem necessary to send multiple SVIDs over the Workload API.  Each workload gets exactly one SVID, but a rolling update transitions workloads from the old to the new in some gradual process over the cluster.  Administrative control over that process feels like an issue best left to control plane implementers, not Workload API specifications.  Am I understanding you correctly, @bri365 ?

**Comment by bri365** [comment]
Your first reading is correct; we are talking about the ordering of SVIDs returned on the Workload API. 

Good catch; the described scenario does not capture the need clearly. In cases where a small subset of workloads need to retain the old SPIFFE ID for some period of time (e.g. for interoperability) while a majority do not, adding the intelligence to the subset would prove most cost effective, and drive the desire for a default. Agreed, this is probably best handled administratively in the long run.

@rturner3 may be able to add additional thoughts.

**Comment by evan2645** [comment]
We have been iterating on this in a google document, which I am porting to markdown here for posterity. It captures the reasoning behind the shape of this change.

# Purpose
This document details considerations and a proposal for adding SVID labels in the SPIFFE Workload API. The intent of this document is to validate the concepts and request feedback.

# Background
While SPIFFE philosophically leans toward workloads having single identities, there are cases where this proves impractical or undesirable. Users are dealing with this today, adding SVID/SPIFFE ID awareness directly into workloads, which is not a recommended practice. This proposal is intended to offer guidance on a more standardized way of addressing this need.

# Use Cases
* Internal vs external IDs - privacy protection for naming schemes  

  Organizations collaborating on a joint engagement require communication between applications. Internal SPIFFE ID naming 
conventions might mandate location, division, group, project and/or user data as naming components. These SPIFFE IDs 
might be undesirable to share with outside organizations.

  In this scenario, a workload would receive two (or more) SVIDs, and for example could be labelled "internal" and "external".

* JWT-SVID Risk Mitigation

  Workload scenarios exist where mTLS connections are not possible with the target endpoints, making the use of JWT-SVIDs necessary. If the caller is a highly privileged workload, it may be desirable to use an alternate SPIFFE ID when calling less trustworthy services due to the bearer token nature of JWTs. Doing so can help reduce the risk of token abuse (i.e. token replay combined with weak audience value or buggy validators).

  In these scenarios, the SVIDs may be labelled "default" and "payments" for example. This concern also applies to the first use case (described above) - due to the nature of JWTs, users may wish to use a different identity when communicating with workloads in other organizations. 

* SPIFFE ID migration

  As organizations adopt SPIFFE and learn about their needs, initial ad hoc SPIFFE ID naming may be updated to more standardized formats. Updating all applications simultaneously is rarely practical. Furthermore, while SPIFFE control planes may implement features akin to staggered roll-outs, it is always desirable to lean on purpose-built tools for this purpose such as configuration management or orchestration systems. In doing so however, workloads must have the option of consuming either the old or the new identity for some period of time.


  Workloads in these scenarios can disambiguate SVIDs in the SPIFFE Workload API response through the use of labels, for example “new” and “old” or “v1” and “v2”. The consuming applications are then configured accordingly (e.g. the orchestration system configures 5% of the apps to use the SVID labelled “new”).

# Worked Example
Let’s focus on the first use case for this example.

E-auction is a company that digitizes processes for real-life auctions. They have a team of assessors, which visits sellers and assesses the items they want to auction. For each item to be sold, the assessors send an e-mail based report to a centralized system. Periodically, these assessments are aggregated, processed, and the results sent via an API call to an auction partner (i.e. the brick-and-mortar auction house that will execute the event).

Due to the sensitive nature of some of the auctions that E-auction services, and the handling of “untrusted” inputs, it is necessary to isolate assessors’ data and processing from one another. To accomplish this, a cron job is deployed for each field assessor, and each job may only access the data of the assessor for which it is running. A SPIFFE ID like the following is chosen for this job:
* spiffe://e-auction.example.com/seattle/assessor/alice/report-cronjob

At the job’s conclusion, the results are compiled into a report and posted to the auction partner for inclusion in the lot. There’s only one problem though: E-auction doesn’t want their auction partners to know about their assessors, and their assessor workforce is volatile. Instead, they want their partners to see reports being posted from a stable E-auction identifier. To do this, the jobs must use a second SVID with a different identity. The following SPIFFE ID is chosen, and is issued to all assessment report cron jobs (in addition to their “native” identity):
* spiffe://e-auction.example.com/auctions/assessments

E-auction doesn’t want to have to configure each cron job with the SPIFFE IDs it should be using, because when the jobs run in staging they get a different ID, and it is important that the job configuration does not change between staging and production. They also don’t want to rely on SPIFFE Workload API response ordering, because the ordering isn’t well defined and the mechanism itself is brittle. Instead, E-Auction chooses to label the SVIDs “internal” and “external”, and configure the jobs as such:
```
{
    email_api_addr = assessor-mail.e-auction.example.com
    email_api_svid_label = “internal”

    partner_id = 1234badcafe
    partner_api_endpoint = https://partner.example.com/auctions/lot
    partner_api_svid_label = “external”
}
```

# Proposal
Add a string field to X509SVID and JWTSVID messages in the workload API, like:
```
  // Optional. Arbitrary string to provide guidance on how this identity
  // should be used by a workload when more than one SVID is returned.
  // As an interoperability consideration, SPIFFE implementations SHOULD
  // support labels up to a maximum of 2048 bytes in length.
  string label = 5;
```

Add the field definition to sections 5.1 and 6.1 of the Workload API document.

Add the following text for clarification to section 5.3 of the Workload API document:

```
As a workload can receive either X.509-SVID or JWT-SVID identities, and multiple identities of either type, the optional `label` field can be used by SPIFFE implementations to deliver guidance to workloads on how a given identity should be used. The SPIFFE specifications do not define the contents of the `label` field.
```

Add example usage for SVID labels to the Workload API document

**Comment by evan2645** [comment]
Closing this out as I believe it's been completed in https://github.com/spiffe/spiffe/pull/179
