### ISSUE TITLE
SPIFFE JWT spec does not match SPIRE

### ISSUE THREAD

**Issue by letmaik** [spiffe/spiffe#188]
The spec at https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md does not include the `iss` claim and in general the way to advertise bundles seems different from OIDC discovery endpoints.

On the other side, SPIRE seems to implement OIDC and includes `iss`. See https://spiffe.io/docs/latest/keyless/oidc-federation-aws/.

What am I missing?

**Comment by evan2645** [comment]
[Section 3](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#3-jwt-claims) states that implementors may include additional claims (such as `iss`). You are correct that SPIFFE bundles and federation is slightly different than OIDC, but SPIRE supports OIDC-based JWT-SVID validation for convenience (and is also why it supports `iss` claim).

These are choices that were made by the SPIRE maintainers, and while they go a little above and beyond what is codified in the specs, nothing about it makes SPIRE non-conformant.

Does this answer your question?

**Comment by evan2645** [comment]
I should clarify that OIDC support in SPIRE is implemented in a separate binary, available here: https://github.com/spiffe/spire/tree/main/support/oidc-discovery-provider

Bundle endpoints served by SPIRE directly are always SPIFFE Federation conformant.

**Comment by letmaik** [comment]
Makes sense, although I find it a bit strange that it's not part of the SPIFFE spec, even as a non-mandatory feature.

The spec says "SPIFFE bundles may contain JWK entries for many different SVID types. Implementations MUST extract the JWT-SVID specific keys before using them for validation purposes". Does SPIRE serve the bundle as-is in the OIDC discovery endpoint? If so, it would seem that validators would violate the spec slightly since they wouldn't know about the extra semantics.

**Comment by evan2645** [comment]
> Makes sense, although I find it a bit strange that it's not part of the SPIFFE spec, even as a non-mandatory feature.

For JWT-SVID, we get to know the issuer implicitly because the identity (`sub`, the SPIFFE ID) is a function of the issuer (in our case, the trust domain name). In general, the specs strive to define what must be defined to accomplish the goals (interop, safety, etc), and things that can be left to the implementor or user are. For example, X509-SVID does not define Subject or Common Name, but an X509-SVID may (and often does) include them.

> The spec says "SPIFFE bundles may contain JWK entries for many different SVID types. Implementations MUST extract the JWT-SVID specific keys before using them for validation purposes". Does SPIRE serve the bundle as-is in the OIDC discovery endpoint?

The OIDC discovery provider does _not_ simply reflect the SPIFFE bundle. Instead, it filters out non-JWT-SVID keys, and (IIRC) removes the SPIFFE-specific `use` values, and serves that. It also serves a basic barebones discovery document etc.

**Comment by evan2645** [comment]
>  it would seem that validators would violate the spec slightly since they wouldn't know about the extra semantics.

It is true that OIDC-based validators do not have the extra knowledge about JWT-SVID. Luckily, this isn't _too_ impactful in practice because most of the constraints placed on the token by the spec are around claims that have well-known semantics (e.g. `exp`). There are a couple places that may get missed, such as validating that `aud` is set, however all major IDPs and validators we've encountered thus far are handling it in a satisfactory way.

SPIRE's support of OIDC is there for interop with services that don't yet support SPIFFE Federation. Ideally, SPIFFE Federation is natively supported. Until then, OIDC mostly suffices.

**Comment by letmaik** [comment]
Thanks for the details, I'll close this as it's in line with the spec.
