### ISSUE TITLE
JWT-SVID additional properties: doc vs. schema

### ISSUE THREAD

**Issue by dana-harrington** [spiffe/spiffe#193]
There appears to be disagreement between the [JWT-SVID document](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#3-jwt-claims) and the [JSON schema](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.schema).
In the document:

> Registered claims not described in this document, in addition to private claims, MAY be used as implementers see fit.

however the JSON schema [expressly forbids this](https://github.com/spiffe/spiffe/blob/7002300cb05797b94102aae0226b90ad2d6424d1/standards/JWT-SVID.schema#L78)

> additionalProperties: false

Is it correct to assume the JSON schema is incorrect/out of date?

**Comment by evan2645** [comment]
Hi @dana-harrington thank you very much for opening this.

The JSON schema is incorrect. @azdagron has volunteered to clean it up in the near future. If you'd like to send a PR in the meantime, we'd gladly accept it. There may be other aspects of the schema that need attention as well.

**Comment by azdagron** [comment]
The [JSON schema](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties) documentation has this to say:
 > The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword or match any of the regular expressions in the patternProperties keyword. By default any additional properties are allowed.

Since our schema includes `patternProperties` presumably we still allow for additional claims to be specified as long as they match the declared pattern. However, I'm not quite sure what the regex in the pattern we have is trying to allow (or prevent!).
