### ISSUE TITLE
Add additional information into the specification to justify choices

### ISSUE THREAD

**Issue by azdagron** [spiffe/spiffe#230]
Some specs have requirements on certain choices (e.g. extended key usage bits on X509-SVID) without the accompanying justification. This can cause confusion and extra work as readers seek out answers from the community (or worse, give up on evaluating).

We should audit the specs and add embellishment, where appropriate, to increase understanding and bring the reader along on the journey of why the specs are shaped the way they are.

**Comment by Rajarshi1998** [comment]
I would like to contribute to fix this issue. Thank you!!

**Comment by evan2645** [comment]
I think we should tackle these as they come up ... that way, we'll have context on the specific confusion and how to clarify, and it's more actionable because the work is focused. For example, @Rajarshi1998 has volunteered to help, but it's hard to understand exactly what needs to be done here and provide the guidance that will lead to a successful outcome

I'm gonna go ahead and close this out, happy to re-open if you feel differently
