### ISSUE TITLE
Clarify 'digitalSignature' basic constraints for SVID signing certificates

### ISSUE THREAD

**Issue by briansmith** [spiffe/spiffe#28]
Note: This issue is NOT what PR #27 is about. This issue is further clarifying things.

The draft spec currently says: “They MUST NOT set `keyEncipherment` or `keyAgreement`. This helps ensure that they cannot be used for authentication purposes.”

However, 

1. The `digitalSignature` key usage has the same issues as `keyEncipherment` or `keyAgreement` with respect to allowing additional non-CA usage of a CA certificate.
2. The check that "CA = true" isn't set in the basic constraint extension during leaf validation already prevents SVID signing certificates from being used as leaf certificates.

I propose that the text “They MUST NOT set `keyEncipherment` or `keyAgreement`" be removed. This helps ensure that they cannot be used for authentication purposes.” be removed.

Failing that, `digitalSignature` should be added to the list, for consistency's sake.

**Comment by rra** [comment]
I think adding `digitalSignature` to the list is the correct fix.  (In a previous draft of this document I'd been under the mistaken impression that `digitalSignature` was required for CAs, but having re-read RFC 5280, this is not the case.)

**Comment by evan2645** [comment]
I was not totally clear on whether `digitalSignature` would be required in order to perform the full set of CA duties (like CRL signing etc). Reading further, I agree with Russ that it is not required for the CRL case.

If we can't come up with any legitimate use cases for `digitalSignature` on a CA cert, then I think we should add the field to the list. While I agree that @briansmith's point 2 should do the job, I'd mildly prefer the belt-and-suspenders approach of specifying this in both the validation and the key usage sections.

**Comment by dudedad** [comment]
I'm good either way.  Generally, I am more verbose... hence like adding Digital Sig to the list of forbidden.

**Comment by briansmith** [comment]
PR #27 fixes this by removing the unnecessary "MUST NOT", instead of by adding "digitalSignature" to the "MUST NOT" list. As noted in that PR, especially in the future there may be valid reasons for the SVID signing certificate to sign things other than X.509 certificates. So this can be closed if/when #27 is merged.

**Comment by evan2645** [comment]
Fixed in #27
