### ISSUE TITLE
Project Proposal for AWS Roles Anywhere credential helper

### ISSUE THREAD

**Issue by amoore877** [spiffe/spiffe#301]
From @strideynet in SPIFFE Slack:
Initial post- https://spiffe.slack.com/archives/C01DNVCF9CP/p1724929980844659
SSC post- https://spiffe.slack.com/archives/C01GQ267JJU/p1724949994035169

"""
## Initial Maintainer List
- Noah Stride (Teleport) - @strideynet
If we need further maintainers, I can draw from other members of my team here at Teleport. I was hoping this could fall under the umbrella of the "tiny projects" maintainer group.
## Purpose
- What specific pain point does the project address?
	- Using the Workload API and SPIFFE X509 SVIDs to authenticate to AWS.
- What does "done" mean for the project? What is the idealized vision for the shape of the project? What are the milestones to complete for each level of [maturity](https://github.com/spiffe/spiffe/blob/main/MATURITY.md)?
	- This project is likely to be quite small and is tightly scoped. Ideally, core functionalitywould be complete within a few weeks and from that point onwards, focus would be on keeping on top of dependency updates/CVEs etc.
- What are the current workarounds or alternative solutions, and why are they inadequate?
	- Regularly invoking spiffe-helper separately to rolesanywhere-credential-helper
		- This works today, and is acceptable in Linux environments with an init system where spiffe-helper can run as a distinct service.
		- This architecture is not well-suited for containerised environments where an init system is not available.
	- Alternative: Using spiffe-helper wrapped around rolesanywhere-credential-helper
		- Problems with spiffe-helper
			- Today, it is not well designed for acting as a "wrapper" around a short-lived binary. For this use-case, it would be ideal if spiffe-helper exited after the underlying command had been executed.
			- Today, it does not support selecting an SVID based on the
			- It is not clear what guarantees are made in regard to the STDOUT of spiffe-helper, if a change is introduced which emits log messages over STDOUT, this will break the credential helper's functionality.
		- Problems with rolesanywhere-credential-helper
			- Pre-built binaries are linked to glibc
			- Pre-built binaries are not available for a wide range of common architectures
	- Alternative: adding AWS Roles Anywhere support directly into spiffe-helper
		- Increases the upstream dependencies of spiffe-helper
	- Alternative: adding SPIFFE support into the rolesanywhere-credential-helper
		- Dependent on AWS accepting this contribution.
		- Dependent on AWS to accept further contributions to improve UX in future or to patch issues.
		- Today, several existing issues with rolesanywhere-credential-helper already make it awkward to use (e.g pre-built binaries are linked to glibc and unavailable for common architectures)
- How does your project align with SPIFFE's overall mission and goals?
	- Eases adoption/reduces barrier to entry of SPIFFE by organisations who wish to use SPIFFE to authenticate to AWS APIs.
	- Acts as "proof" that SPIFFE interoperates with other platforms/demonstrates potential use-cases - encouraging organisations to consider adopting SPIFFE.
	- Authenticating with AWS seems a common-enough use-case that this is valuable enough to fall under the SPIFFE umbrella.
- Who are the primary end-users or beneficiaries of this project?
	- Organizations who wish to use SPIFFE to authenticate to AWS APIs, typically from workloads not hosted in AWS.
## Direction
- What is the project’s roadmap for the next 6-12 months?
	- MVP: Working authentication to AWS APIs using AWS Roles Anywhere and a SPIFFE Workload API endpoint.
	- Future improvements:
		- Ability to specify which X509 SVID should be selected based on a hint.
		- Upstreaming improvements to the rolesanywhere-credential-helper library to this binary
		- E2E testing to assert that this implementation and AWS continues to be compatible with SPIFFE for authentication.
- What are practices or styles that will be encouraged or discouraged?
	- Standard Go best practices, testing etc.
- How will the project scale? What are the scalability goals?
	- I do not expect the project to "scale", it's fairly tightly scoped.
- Are there any legal or ethical considerations?
	- Use of AWS product name
	- Use of AWS library
		- Licensed under Apache License 2.0 - so I expect this to be a non-problem.
- What are potential challenges, and how do you plan to overcome them?
	- Keeping up with upstream changes introduced in the library published by AWS
		- History seems to indicate that they do not often make changes to this API or to the library itself. A small group of maintainers should be able to stay on top of this.
- What kind of community involvement do you foresee (e.g., are there opportunities for novice contributors, or is the project more suitable for experts in the field?)
	- To be honest, I expect the project to be "done" within a fairly short amount of time and then to enter a period of maintenance. It will be approachable to novice contributors but I do think it is unlikely there will be much work to complete.
- What technologies will the project leverage, and are they aligned with the larger ecosystem?
	- Go
		- Aligned with most SPIFFE and CNCF projects
- How will the project maintain data integrity, security, and privacy?
	- Sensitive information will not be included in logs.
	- Project will use automated tooling (e.g dependabot) to keep on top of dependency updates
	- Project will include a test suite to verify functionality.
- Are there any possible collaborations with existing SPIFFE projects?
	- This project could lead to upstream changes in the spiffe-go SDK
- How will your project deal with failure scenarios or fallbacks?
	- Unsure how to answer this
## Governance
- How will maintainers be added or removed? What is the goal number of maintainers?
	- The goal would be to have 2-3 maintainers. The project is fairly simple. Ideally, the project would fall under the "tiny project" maintainers group which I'd be happy to join.
- How often will the maintainers meet?
	- Synchronous meetings seem unnecessary for a project of this size.
- How will maintainers interact with contributors and review their Pull Requests and Issues? Slack? Dedicated online meetings? What is the goal turn around time?
	- Interaction within GitHub Issues and Pull Requests and Slack seems sufficient.
	- Target to respond to tickets within 1 week.
	- Target to respond to security-sensitive issues within 2 working days.
- What conflict resolution mechnisms will the maintainers follow? (e.g., allocated debate time? Majority vote? Unanimous vote for certain topics? What is the SLO for resolution?)
	- Unsure - I'd be happy to adopt any standard SPIFFE governance practices here.
## Similar Projects
- Do similar projects already exist actively within the SPIFFE community? If so, what makes this project sufficiently unique to justify any overlap?
	- Whilst this functionality could be built into spiffe-helper, I'm concerned that it would bloat it's currently fairly tightly-scoped purpose and implementation.
- Do similar projects exist outside of SPIFFE that can better help us understand the project's value?
	- N/A
- Has this project existed in the past but was abandoned or closed out? What is different in today's world?
	- As far as I am aware, no.
"""

**Comment by amoore877** [comment]
Thanks for the proposal @strideynet :)

Me and @kfox1111  already discussed a bit in slack with you, leading to this issue being created. 

Please allow a bit of time for the rest of SSC to catch up and form their own opinions or questions, and we'll get back to you.

Of course, we also welcome comments from the rest of the SPIFFE community or any other concerned parties as well.

**Comment by v0lkan** [comment]
Great proposal @strideynet.

Here are some of my remarks and suggestions:

* We might want to clarify the "tiny projects" maintainer group. While it makes sense internally, having a link to a page there would be good. Or maybe a link to <https://github.com/spiffe/spiffe/blob/main/NEW_PROJECTS.md> 
 
tangential: @amoore877 (and anyone interested: Is the maintainer of "tiny projects" 'entity' the SSC at the moment?


Wrt, current workarounds and problems: Highlighting a specific example where the pre-built binaries fail—I don't know: maybe a list of common architectures affected) would help justify the scope of the problem.

About alignment with SPIFFE's mission:

It's a great that this project reduces barriers to SPIFFE adoption. That said, it would be nice to have how this will be used in practice (for e.g., securing workloads in hybrid clouds, or maybe something similar)

Wrt Primary End Users:
This section is concise and clear. 

It makes sense to target organizations working with non-AWS-hosted workloads, but maybe elaborate a bit on whether this is primarily enterprises or smaller organizations as well.
(I'm not sure about that, but wanted to share while thinking out loud)

On Roadmap:

I think things are not clear yet, but E2E testing might need some clarity. What does it entail? How do we ensure SPIFFE compatibility? Is there are contingency plan if an AWS API is updated, and things like that.

Wrt Community:
* To hear the honesty is refreshing.
* If the project is going to be done soon; we might need to clarify what kind of ongoing contributions (if any) it will need. — if the project does not need too much of a maintenance; we might just skip that. But I'm sure there will be needs for bugfixes, documentation updates, and other things that a new/novice contributor may want to get involved with.

Governance:
* I'd suggest defining a clear conflict resolution mechanism (even if it's merely escalating things to SSC). With a single contributor that might feel an overkill; but if the project grows, it might be good to set boundaries beforehand.

On "Similar Projects"
* You may want to mention how this project will maintain clear boundaries and avoid scope creep to prevent bloat (similar to how spiffe-helper is kept minimal) — what would reassure and resonate with potential 

(another tangential question (and playing devil's advocate) is: Do we need to keep spiffe-helper lean? Is there a performance concern, complexity concern, development resource concern (i.e. not enough maintainers) — but that's a separate side thought not related to this PR.)

On Challenges:
* It might be helpful to note what monitoring will be done to stay aware of AWS changes—especially for security-related and breaking functionality changes.

Handling Failure Scenarios:
* Even if we are not sure how to handle failure; it would be worthwhile to list potential risks (i.e., what happens when there is API downtime; what about a breaking change in a dependency) - you can always state that you will be adding monitoring or fallback mechanisms to address them.

Those are all I have at the moment. 

Overall, great proposal.

Thanks for your hard work 🙏 .

**Comment by strideynet** [comment]
> but maybe elaborate a bit on whether this is primarily enterprises or smaller organizations as well.

For the most part, it feels like accessing AWS from non-AWS hosted workloads seems to be much more common amongst enterprises with complex multi-cloud or heterogeneous infra. However, it's definitely not exclusive - I know of smaller startups that are hosting compute on-prem and leveraging some AWS APIs (e.g S3).

> I think things are not clear yet, but E2E testing might need some clarity. What does it entail? How do we ensure SPIFFE compatibility?

My gut feeling here was to spin up an AWS project with Tofu or similar, and have a nightly/on PR job that uses the AWS Roles Anywhere credential helper to exchange a SPIFFE credential for an AWS identity and perform some simple action with the AWS CLI e.g (list buckets under account). It felt like the simplest way to assert the whole thing works end to end. 

>  But I'm sure there will be needs for bugfixes, documentation updates, and other things that a new/novice contributor may want to get involved with.

Agreed - there's definitely scope for docs/fixes that would be welcome from novice contributors. I'm keen to welcome/support contributions if there are folks who wish to make them, regardless of their level of experience - just mostly aware that on the feature/codebase front, there's not a lot of potential work to complete.

> I'd suggest defining a clear conflict resolution mechanism (even if it's merely escalating things to SSC). With a single contributor that might feel an overkill; but if the project grows, it might be good to set boundaries beforehand.

Agreed. If the SSC are happy to be escalated to, then I'm happy for that to be the formal conflict resolution mechanissm.

> You may want to mention how this project will maintain clear boundaries and avoid scope creep to prevent bloat (similar to how spiffe-helper is kept minimal) — what would reassure and resonate with potential

Yeah, I think the simplest way of doing that will be to ensure we set a clear scope in the README, and then making sure we assess incoming feature request tickets etc against that scope. 

> It might be helpful to note what monitoring will be done to stay aware of AWS changes—especially for security-related and breaking functionality changes.

Yeah, I'm open to feedback here, if anyones aware of a way to subscribe to AWS news on a specific product, I'd be keen to send that into a "aws-roles-anywhere" slack channel in the SPIFFE slack so we can triage as appropriate.

---

As a side note, since this issue was opened on my behalf, I can't edit the original text in the issue body. Should I re-open this under my account ?

**Comment by amoore877** [comment]
> tangential: @amoore877 (and anyone interested: Is the maintainer of "tiny projects" 'entity' the SSC at the moment?

yes :) we initially made it SSC until a time where others might volunteer their time to it

> As a side note, since this issue was opened on my behalf, I can't edit the original text in the issue body. Should I re-open this under my account ?

could also just post again here with the "official" proposal :) it's not buried down too far

**Comment by kfox1111** [comment]
Lost track of this. What is the current status?

**Comment by amoore877** [comment]
oh apologies, yes forgot about this.

we've gotten no objections and it's been three weeks, so I think we are good to proceed once @v0lkan 's comments are addressed (could re-post here or make new issue)

**Comment by strideynet** [comment]
I'll raise a new issue with those elements addressed next week - apologies - had a busy month with conferences and such but my schedule is looking clearer now!

**Comment by strideynet** [comment]
See https://github.com/spiffe/spiffe/issues/307 for the replacement GitHub issue - feel free to close this one out :)

**Comment by kfox1111** [comment]
This was setup. Closing the issue.
