### ISSUE TITLE
Clarify the "one SPIFFE ID is allowed per certificate" rules

### ISSUE THREAD

**Issue by briansmith** [spiffe/spiffe#32]
The specification should explain why only one SPIFFE ID is allowed per certificate.

The specification should indicate whether a validator is required to reject a leaf certificate with multiple SPIFFE IDs, or otherwise what should happen during validation when multiple SPIFFE IDs are present in a leaf certificate.

The specification should indicate whether a validator is required to reject a signing certificate with multiple SPIFFE IDs, or otherwise what should happen during validation when multiple SPIFFE IDs are present in a signing certificate.

**Comment by y2bishop2y** [comment]
The reason we specified 1 SPIFFE ID per SVID was to keep things simple. How would we determine what SPIFFE ID in the SVID would be used? An entity with multiple SPIFFE ID would have multiple SVID assigned to it.  Just didn't know how we would determine what ID to use, since different libraries return SAN list differently, we couldn't guarantee that the 0 entry in the parsed array was the "default" value to use  (without using some decoration or parameter on the SPIFFE ID URI, ie spiffe://<domain>/path?default=true. )

That being said, should we reject multiple SPIFFE ID URI values in a SAN for a single SVID ?  Would make sense, could be relaxed later in a different version of SPIFFE standard, if we determine a way to have some sort of order or precedence for a list of URI SPIFFE SAN values.

**Comment by dennisgove** [comment]
> How would we determine what SPIFFE ID in the SVID would be used

If an SVID contains multiple certificates and thus multiple SPIFFE IDs (one per certificate) is there a guaranteed order of those? If SPIRE server config contains `upstream_bundle = true` the SVID will contain N certificates, one for each entry in the trust chain, and each will contain its own SPIFFE ID.

iirc the appropriate way to extract the workload's SPIFFE ID would be to look for the (?only?) leaf certificate in the SVID, is that correct?

**Comment by justinburke** [comment]
> If an SVID contains multiple certificates

Hi @dennisgove, an SVID is an abstract document whose purpose is to carry a SPIFFE ID. (https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE.md#3-the-spiffe-verifiable-identity-document). SPIFFE currently defines two types of SVIDs: JWT-SVID and X509-SVID. In the case of an X509-SVID, the SPIFFE ID is carried in a (single) X.509 certificate.

The name `upstream_bundle` suggests to me that there is a bundle, ie. a collection, of X509-SVID certificates. You'll need to verify with the SPIRE group (this is GitHub repo is for the SPIFFE Standards and Community), the appropriate ordering of certificates in the bundle. Many (but not all) systems use a Server, Intermediates, Root ordering. (https://www.digicert.com/ssl-support/pem-ssl-creation.htm)

**Comment by azdagron** [comment]
The SVID is the leaf certificate (i.e. the first certificate in the chain returned by SPIRE). The remaining certificates are the intermediates necessary to chain the SVID back to a CA in the trust bundle. The fact that those intermediates may also have SPIFFE IDs is immaterial (and is an implementation detail in SPIRE).

Relevant bit from the specification:
```
message X509SVID {
    ...

    // ASN.1 DER encoded certificate chain. MAY include intermediates,
    // the leaf certificate (or SVID itself) MUST come first.
    bytes x509_svid = 2;
```
