### ISSUE TITLE
Naive question: Why the name is SPIFFE

### ISSUE THREAD

**Issue by savankumargudaas** [spiffe/spiffe#93]
Hello Awsome Spiffes!!
As a biggner when I looked over the name of SPIFFE, it looks bit strange to me.
SPIFFE: Secure Production Identity Framework For Everyone

1. Firstly is it a framework/specification/protocol?
2. If it's a framework, does it only applicable to Production? Otherwise what does Production mean?
3. Why "Everyone" is included in name, it's upto those who uses it. There is no protocol/framework (ex: FTP, HTTP etc.) which claims it's for for everyone.
4. Does the name choosen deliberately?

Can someone among who came-up with this name, share there thoughts(/justify)?

**Comment by ajessup** [comment]
Hi Savankumar, I'll let @jbeda (who actually came up with the name SPIFFE) keep me honest here, but the genesis of the name derives from [GIFEE](https://github.com/GIFEE/GIFEE) (Google Infrastructure For Everyone Else), which is a term that I believe the folks from CoreOS first popularized. 

In the same way that projects like Hadoop, HBase, Kubernetes and Prometheus were inspired by existing systems at Google, so too was SPIFFE inspired by internal infrastructure at Google (as well as other companies running highly scaled production workload identity infrastructure, including [Facebook](https://www.youtube.com/watch?v=kY-Bkv3qxMc) and [Netflix](https://www.youtube.com/watch?v=15H5uCj1hlE)). As with those other projects, the goal of SPIFFE was to take capabilities previously only available to developers at these large companies, and make them available to "everyone".

To answer your specific questions:

**Firstly is it a framework/specification/protocol?**
The [SPIFFE](https://github.com/spiffe/spiffe) project itself can be best thought of as a specification (that vendors can implement). The [SPIRE](https://github.com/spiffe/spire) project is an implementation of that specification. SPIRE has a very flexible architecture and thus can also be thought of as a framework for delivering SPIFFE IDs across a wide variety of environments. There are projects other than SPIRE as well that are implementing some or all of the SPIFFE specification.

When SPIFFE was first started "SPIFFE" referred to both the implementation and the specification, but since the latter was maturing faster than the former and other projects wanted to adopt the spec we decided to separate them.

**If it's a framework, does it only applicable to Production? Otherwise what does Production mean?**
It applies wherever you need it, not just production :) The word production simply means that it is intended for production use. The security requirements for production infrastructure are much higher in many cases than for, say, development or testing - and that has had a large influence on the design of SPIFFE and more importantly SPIRE.

**Why "Everyone" is included in name, it's up to those who uses it. There is no protocol/framework (ex: FTP, HTTP etc.) which claims it's for for everyone.**
The word "Everyone" in the name is inherited from the acronym "GIFEE" as described above. GIFEE was a well known term to the authors of the project at the time.

**Does the name chosen deliberately?**
Hopefully the answers above help explain the name!
